#logging:
#    level:
  #    ROOT: DEBUG
#    ca.uhn.fhir.rest.server: DEBUG

server:
    port: 6083
    use-forward-headers: true
    session:
        cookie:
            http-only: true
    contextPath: /phr
    tomcat:
      max-threads: 600


spring:
    application:
        name: phr
    thymeleaf:
        prefix: classpath:/WEB-INF/templates/
    profiles:
        active: dev
    jpa:
       properties:
              format_sql: true
              show-sql: true
              jdbc:
                  batch_size: 20
              cache:
                  use_query_cache: false
                  use_second_level_cache: false
                  use_structured_entries: false
                  use_minimal_puts: false
              search:
                  default:
                      directory_provider: filesystem
                      indexBase: build/lucenefiles
                      worker:
                          execution: sync
                  lucene_version: LUCENE_CURRENT
---
spring:
    profiles: dev
    jpa:
       generate-ddl: true
       hibernate:
              ddl-auto: update
