#logging:
#    level:
  #    ROOT: DEBUG
#    ca.uhn.fhir.rest.server: DEBUG

server:
    port: 6083
    use-forward-headers: true
    session:
        cookie:
            http-only: true
    contextPath: /phr
    tomcat:
      max-threads: 600
app:
    data:
        feed_on_start: true

        # NOTE: keep the resources in order!
        # The resources have references to one another.
        # Add new resources to the end of the list.

        resources:
            - file: datasets/Hengitystietulehdusoireiden_itsearvio_fixed_id1.json
              use_update: false
              
            - file: datasets/location1.json
            - file: datasets/organization1.json
            - file: datasets/healthcareservice1.json
            - file: datasets/practitioner1.json
            - file: datasets/practitioner2.json
            - file: datasets/practitioner3.json
            - file: datasets/person-practitioner1.json
            - file: datasets/person-practitioner2.json
            - file: datasets/person-practitioner3.json
            - file: datasets/practitioner1-role.json
            - file: datasets/practitioner2-role.json
            - file: datasets/practitioner3-role.json
            - file: datasets/practitioner-role-valueset.json
            - file: datasets/PATIENT1/patient.json
            - file: datasets/PATIENT1/person.json
            - file: datasets/PATIENT1/careteam-authorization.json
            - file: datasets/PATIENT1/careteam-care.json
            - file: datasets/PATIENT1/episodeofcare.json
            - file: datasets/PATIENT1/careplan.json
            - file: datasets/PATIENT1/communication.json
            - file: datasets/PATIENT1/observation1.json
            - file: datasets/PATIENT1/observation2.json
            - file: datasets/PATIENT1/observation3.json
            - file: datasets/PATIENT1/observation4.json
            - file: datasets/PATIENT1/observation5.json
            - file: datasets/PATIENT1/observation6.json
            - file: datasets/PATIENT1/observation7.json
            - file: datasets/PATIENT1/communication-notification1.json
            - file: datasets/PATIENT1/communication-notification2.json
            - file: datasets/PATIENT2/patient.json
            - file: datasets/PATIENT2/person.json
            - file: datasets/PATIENT2/observation.json
            - file: datasets/PATIENT2/episodeofcare.json
            - file: datasets/PATIENT2/careteam-authorization.json
            - file: datasets/PATIENT2/careplan.json
            - file: datasets/PATIENT2/communication.json
            - file: datasets/PATIENT2/careteam-care.json
            - file: datasets/careteam3-authorization.json
            - file: datasets/PATIENT3/patient.json
            - file: datasets/PATIENT3/person.json
            - file: datasets/PATIENT3/episodeofcare.json
            - file: datasets/PATIENT3/careplan.json
            - file: datasets/PATIENT3/careteam-care.json
            - file: datasets/PATIENT4/patient.json
            - file: datasets/PATIENT4/person.json
            - file: datasets/PATIENT4/episodeofcare.json
            - file: datasets/PATIENT4/careplan.json
            - file: datasets/PATIENT4/careteam-care.json
            - file: datasets/feedback-issue.json
            - file: datasets/feedback-satisfaction.json

            - file: profiles/ODA-ActivityDefinition.profile.xml
              use_update: false
            - file: profiles/ODA-CarePlan.profile.xml
              use_update: false
            - file: profiles/ODA-CareTeam.profile.xml
              use_update: false
            - file: profiles/ODA-Communication.profile.xml
              use_update: false
            - file: profiles/ODA-EpisodeOfCare.profile.xml
              use_update: false
            - file: profiles/ODA-Goal.profile.xml
              use_update: false
            - file: profiles/ODA-MedicationStatement.profile.xml
              use_update: false
            - file: profiles/ODA-Observation.profile.xml
              use_update: false
            - file: profiles/ODA-Organization.profile.xml
              use_update: false
            - file: profiles/ODA-Person.profile.xml
              use_update: false
            - file: profiles/ODA-Practitioner.profile.xml
              use_update: false
            - file: profiles/ODA-Questionnaire.profile.xml
              use_update: false
            - file: profiles/ODA-QuestionnaireResponse.profile.xml
              use_update: false
            - file: datasets/questionnaires/Oikeus_henkilokohtaiseen_apuun.json
              use_update: false

            - file: datasets/APPOINTMENT/ODALocation-example.json
            - file: datasets/APPOINTMENT/ODAOrganization-example.json
            - file: datasets/APPOINTMENT/ODAPatient-example.json
            - file: datasets/APPOINTMENT/ODAPractitioner-example.json
            - file: datasets/APPOINTMENT/ODASchedule-example.json
            - file: datasets/APPOINTMENT/ODASlot-example.json
            - file: datasets/APPOINTMENT/ODAHealthcareService-example.json
            - file: datasets/APPOINTMENT/ODACareTeam-example.json
            - file: datasets/APPOINTMENT/ODAAppointment-example.json


spring:
    application:
        name: phr
    thymeleaf:
        prefix: classpath:/WEB-INF/templates/
    profiles:
        active: dev
    jpa:
       properties:
              format_sql: true
              show-sql: true
              jdbc:
                  batch_size: 20
              cache:
                  use_query_cache: false
                  use_second_level_cache: false
                  use_structured_entries: false
                  use_minimal_puts: false
              search:
                  default:
                      directory_provider: filesystem
                      indexBase: build/lucenefiles
                      worker:
                          execution: sync
                  lucene_version: LUCENE_CURRENT
---
spring:
    profiles: dev
    jpa:
       generate-ddl: true
       hibernate:
              ddl-auto: update
