server:
    port: 6083
    use-forward-headers: true
    session:
        cookie:
            http-only: true
    contextPath: /phr

spring:
    datasource:
        url: jdbc:derby:directory:build/jpaserver_derby_files;create=true
        username:
        password:
        driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    profiles:
      active: dstu2
logging:
    level:
#    ROOT: DEBUG
#    ca.uhn.fhir.rest.server: DEBUG

