server:
    port: 6083
    use-forward-headers: true
    session:
        cookie:
            http-only: true
    contextPath: /phr

spring:
    application:
        name: phr
    datasource:
        url:  jdbc:derby:memory:odaDB;create=true
        username:
        password:
        driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    thymeleaf:
        prefix: classpath:/WEB-INF/templates/
    profiles:
        active: dstu3
    
logging:
    level:
#    ROOT: DEBUG
#    ca.uhn.fhir.rest.server: DEBUG

