#logging:
#    level:
  #    ROOT: DEBUG
#    ca.uhn.fhir.rest.server: DEBUG

server:
    port: 6083
    use-forward-headers: true
    session:
        cookie:
            http-only: true
    contextPath: /phr
    tomcat:
      max-threads: 600
app:
    data:
        feed_on_start: false
        resources:               
            hengitystieoirearvio:
               file: datasets/Hengitystietulehdusoireiden_itsearvio_fixed_id1.json
               use_update: false
               #Note: use_update defaults to true if not defined
               injector: fi.oda.phr.dataset.ResourceInjector
               #      order and file must be defined. They have no default values.
               order: -1

            activitydefinition-rfc:
               file: profiles/ODA-ActivityDefinition.profile.xml
               use_update: false
               order: 0
            careplan-rfc:
               file: profiles/ODA-CarePlan.profile.xml
               use_update: false
               order: 0
            careteam-rfc:
               file: profiles/ODA-CareTeam.profile.xml
               use_update: false
               order: 0
            communication-rfc:
               file: profiles/ODA-Communication.profile.xml
               use_update: false
               order: 0
            episodeofcare-rfc:
               file: profiles/ODA-EpisodeOfCare.profile.xml
               use_update: false
               order: 0
            goal-rfc:
               file: profiles/ODA-Goal.profile.xml
               use_update: false
               order: 0
            medicationstatement-rfc:
               file: profiles/ODA-MedicationStatement.profile.xml
               use_update: false
               order: 0
            observation-rfc:
               file: profiles/ODA-Observation.profile.xml
               use_update: false
               order: 0
            organization-rfc:
               file: profiles/ODA-Organization.profile.xml
               use_update: false
               order: 0
            person-rfc:
               file: profiles/ODA-Person.profile.xml
               use_update: false
               order: 0
            practitioner-rfc:
               file: profiles/ODA-Practitioner.profile.xml
               use_update: false
               order: 0
            questionnaire-rfc:
               file: profiles/ODA-Questionnaire.profile.xml
               use_update: false
               order: 0
            questionnaireresponse-rfc:
               file: profiles/ODA-QuestionnaireResponse.profile.xml
               use_update: false
               order: 0

            oikeus_apuun:
               file: datasets/questionnaires/Oikeus_henkilokohtaiseen_apuun.json
               use_update: false           
               order: 1
               
            location1:
               file: datasets/location1.json
               order: 2
    
            organization1:
               file: datasets/organization1.json
               order: 3
               
            healthcareservice1:
               file: datasets/healthcareservice1.json
               order: 4
               
            practitioner1:
               file: datasets/practitioner1.json
               order: 5
               
            practitioner2:
               file: datasets/practitioner2.json
               order: 6
    
            practitioner3:
               file: datasets/practitioner3.json
               order: 7
                          
            person-practitioner2:
               file: datasets/person-practitioner2.json
               order: 8
    
            person-practitioner3:
               file: datasets/person-practitioner3.json
               order: 9
    
            patient1:
               file: datasets/PATIENT1/patient.json
               order: 10
    
            patient1-person:
               file: datasets/PATIENT1/person.json
               order: 11
    
            patient1-careteam-authorization:
               file: datasets/PATIENT1/careteam-authorization.json
               order: 12
    
            patient1-careteam-care:
               file: datasets/PATIENT1/careteam-care.json
               order: 13
    
            patient1-episodeofcare:
               file: datasets/PATIENT1/episodeofcare.json
               order: 14
    
            patient1-careplan:
               file: datasets/PATIENT1/careplan.json
               order: 15
    
            patient1-communication:
               file: datasets/PATIENT1/communication.json
               order: 16
            
            patient1-observation1:
               file: datasets/PATIENT1/observation1.json
               order: 16
    
            patient1-observation2:
               file: datasets/PATIENT1/observation2.json
               order: 17
               
            patient1-observation3:
               file: datasets/PATIENT1/observation3.json
               order: 18
               
            patient1-observation4:
               file: datasets/PATIENT1/observation4.json
               order: 19
               
            patient1-observation5:
               file: datasets/PATIENT1/observation5.json
               order: 20
               
            patient1-observation6:
               file: datasets/PATIENT1/observation6.json
               order: 21                    
    
            patient1-observation7:
               file: datasets/PATIENT1/observation7.json
               order: 22
    
            patient2:
               file: datasets/PATIENT2/patient.json
               order: 25
    
            patient2-person:
               file: datasets/PATIENT2/person.json
               order: 26
    
            patient2-observation:
               file: datasets/PATIENT2/observation.json
               order: 27
    
            patient2-episodeofcare:
               file: datasets/PATIENT2/episodeofcare.json
               order: 28
    
            patient2-careteam-authorization:
               file: datasets/PATIENT2/careteam-authorization.json
               order: 29
    
            patient2-careplan:
               file: datasets/PATIENT2/careplan.json
               order: 30
               
            patient2-communication:
               file: datasets/PATIENT2/communication.json
               order: 31
               
            patient2-careteam-care:
               file: datasets/PATIENT2/careteam-care.json
               order: 32
                                     
            careteam3-authorization:
               file: datasets/careteam3-authorization.json
               order: 33
    
            patient3:
               file: datasets/PATIENT3/patient.json
               order: 34
               
            patient3-person:
               file: datasets/PATIENT3/person.json
               order: 35
               
            patient3-episodeofcare:
               file: datasets/PATIENT3/episodeofcare.json
               order: 36
    
            patient3-careplan:
               file: datasets/PATIENT3/careplan.json
               order: 37
    
            patient3-careteam-care:
               file: datasets/PATIENT3/careteam-care.json
               order: 38
    
            patient4:
               file: datasets/PATIENT4/patient.json
               order: 39
    
            patient4-episodeofcare:
               file: datasets/PATIENT4/episodeofcare.json
               order: 40
    
            patient4-careplan:
               file: datasets/PATIENT4/careplan.json
               order: 41
    
            patient4-careteam-care:
               file: datasets/PATIENT4/careteam-care.json
               order: 42
    
            patient4-feedback-issue:
               file: datasets/feedback-issue.json
               order: 43
            
            patient4-feedback-satisfaction:
               file: datasets/feedback-satisfaction.json
               order: 44


spring:
    application:
        name: phr
    thymeleaf:
        prefix: classpath:/WEB-INF/templates/
    profiles:
        active: dev
    jpa:
       properties:
              format_sql: true
              show-sql: true
              jdbc:
                  batch_size: 20
              cache:
                  use_query_cache: false
                  use_second_level_cache: false
                  use_structured_entries: false
                  use_minimal_puts: false
              search:
                  default:
                      directory_provider: filesystem
                      indexBase: build/lucenefiles
                      worker:
                          execution: sync
                  lucene_version: LUCENE_CURRENT
---
spring:
    profiles: dev
    jpa:
       generate-ddl: true
       hibernate:
              ddl-auto: update
